### ISSUE TITLE
Challenge 1 Feedback

### ISSUE THREAD

**Issue by meredithcat** [noltron000/graph-assignments#1]
Challenge 1 Feedback: 7/20
Feedback based on Challenge 1 Rubric

- Solution: 2 (x2 = 4)
  - 'D' and 'G' should be flipped - Graph has edges going in both directions, Digraph has edges going in one direction
  - If new edge contains a vertex not in the vertex list, should add the new vertex or throw an exception

- Documentation: 1
  - Add docstrings and class level comments

- Organization: 2
  - Graph class should not contain any logic for file reading or I/O. Have a separate function(s) or class(es) to handle that and create the graph.

- Testing: 0
  - Add unit tests

**Comment by meredithcat** [comment]
Challenge 1 Feedback (Resubmit): 10/20

- Solution: 2 (x2 = 4)
  - Running on a file with edge weights produces an error.
<img width="501" alt="Screen Shot 2019-08-12 at 10 53 58 PM" src="https://user-images.githubusercontent.com/351124/62918313-1ba1c580-bd54-11e9-9885-b84217523d2b.png">


- Documentation: 3
  - Comments look great. Small note - it is not necessary to describe the entire function's algorithm in a docstring. You can do that in block-level comments.

- Organization: 3
  - Classes and functions are loosely coupled

- Testing: 0
  - No unit tests

**Comment by noltron000** [comment]
edge weights now work properly. 👍

**Comment by noltron000** [comment]
Recent changes should fulfill the requirements of this task.
